///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace sfdcTestScripts
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the sfdcTestScriptsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("240c583a-9a1d-4ab6-8bf8-b2ef22bf5977")]
    public partial class sfdcTestScriptsRepository : RepoGenBaseFolder
    {
        static sfdcTestScriptsRepository instance = new sfdcTestScriptsRepository();

        /// <summary>
        /// Gets the singleton class instance representing the sfdcTestScriptsRepository element repository.
        /// </summary>
        [RepositoryFolder("240c583a-9a1d-4ab6-8bf8-b2ef22bf5977")]
        public static sfdcTestScriptsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public sfdcTestScriptsRepository() 
            : base("sfdcTestScriptsRepository", "/", null, 0, false, "240c583a-9a1d-4ab6-8bf8-b2ef22bf5977", ".\\RepositoryImages\\sfdcTestScriptsRepository240c583a.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("240c583a-9a1d-4ab6-8bf8-b2ef22bf5977")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class sfdcTestScriptsRepositoryFolders
    {
    }
#pragma warning restore 0436
}
